name: .NET CI/CD Pipeline

on:
  push:
    branches: [ master ]

env:
  DOTNET_VERSION: '9.0'
  AZURE_WEBAPP_NAME: 'bond-valuation-api'
  ACR_REGISTRY: 'bondvaluationassessment.azurecr.io'
  IMAGE_NAME: 'bond-valuation-service'
  RESOURCE_GROUP: 'BondValuationAssessment'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Application/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/bondsvaluationservice:latest
          ${{ secrets.DOCKER_USERNAME }}/bondsvaluationservice:${{ github.sha }}

  deploy-to-azure:
    needs: build-and-push-docker
    runs-on: ubuntu-latest
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name ${{ env.ACR_REGISTRY }}

    - name: Pull from Docker Hub and push to ACR
      run: |
        # Pull from Docker Hub
        docker pull ${{ secrets.DOCKER_USERNAME }}/bondsvaluationservice:${{ github.sha }}
        
        # Tag for ACR
        docker tag ${{ secrets.DOCKER_USERNAME }}/bondsvaluationservice:${{ github.sha }} ${{ env.ACR_REGISTRY }}/samples/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
        # Push to ACR
        docker push ${{ env.ACR_REGISTRY }}/samples/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Update App Service container configuration
      run: |
        az webapp config container set \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --container-image-name ${{ env.ACR_REGISTRY }}/samples/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Restart App Service
      run: |
        az webapp restart \
          --name ${{ env.AZURE_WEBAPP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }}
