name: Simple Test Workflow

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  simple-test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Print hello
      run: echo "Hello! The workflow is running."
      
    - name: List files
      run: dir
